<?php

/*
 * This file is part of the Snowtricks community website.
 *
 * GOMEZ José-Adrian j.gomez17@hotmail.fr
 *
 */

namespace ST\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    /**
    * Get all the comments of one tricks
    *
    * @param trickId  $trickId
    * @param approved $approved
    *
    * @return Comments
    */
    public function getCommentsForTrick($trickId, $approved = true)
    {
        $qb = $this->createQueryBuilder('c')->select('c')->where('c.trick = :trick_id')
        ->addOrderBy('c.created')->setParameter('trick_id', $trickId);

        if (false === is_null($approved)) {
            $qb->andWhere('c.approved = :approved')->setParameter('approved', $approved);
        }

        return $qb->getQuery()->getResult();
    }//end getCommentsForTrick()
}//end class
