<?php

namespace ST\PlatformBundle\Repository;

/**
 * FigureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigureRepository extends \Doctrine\ORM\EntityRepository
{
}
