st_platform_homepage:
    path:     /
    defaults: { _controller: STPlatformBundle:Index:index }

st_platform_trick:
    path:  /afficher/{slug}
    defaults:
        _controller: STPlatformBundle:Tricks:show
        methods: [POST]

st_platform_add:
    path:      /add
    defaults:
        _controller: STPlatformBundle:Tricks:add

st_platform_edit:
    path:      /modif/{id}
    defaults:
        _controller: STPlatformBundle:Tricks:edit

st_platform_supp:
    path:      /supp/{id}
    defaults:
        _controller: STPlatformBundle:Tricks:supp







