services:
#    st_platform.example:
#        class: ST\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
# Fixtures services
    ST\PlatformBundle\DataFixtures\ORM\AppFixture:
        tags: [doctrine.fixture.orm]
    st_platform.videoConverter:
      class: ST\PlatformBundle\Services\VideoConverter
    st_platform.EditMedia:
      class: ST\PlatformBundle\Services\EditMedia